// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as JsxRuntime from "react/jsx-runtime";

function Input(props) {
  var onSubmit = props.onSubmit;
  var match = React.useState(function () {
        return "";
      });
  var setText = match[1];
  var text = match[0];
  var handleInputChange = function ($$event) {
    var value = $$event.currentTarget.value;
    setText(function (param) {
          return value;
        });
  };
  var handleButtonClick = function (param) {
    if (text !== "") {
      onSubmit(text);
      return setText(function (param) {
                  return "";
                });
    }
    
  };
  var handleKeyDown = function (e) {
    var key = e.key;
    if (key !== "Enter") {
      return ;
    }
    e.preventDefault();
    onSubmit(text);
    setText(function (param) {
          return "";
        });
  };
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("input", {
                      className: "input input-bordered mr-1 w-full",
                      placeholder: "Type here",
                      type: "text",
                      value: text,
                      onKeyDown: handleKeyDown,
                      onChange: handleInputChange
                    }),
                JsxRuntime.jsx("button", {
                      children: JsxRuntime.jsx("svg", {
                            children: JsxRuntime.jsx("path", {
                                  d: "M15.854.146a.5.5 0 0 1 .11.54l-5.819 14.547a.75.75 0 0 1-1.329.124l-3.178-4.995L.643 7.184a.75.75 0 0 1 .124-1.33L15.314.037a.5.5 0 0 1 .54.11ZM6.636 10.07l2.761 4.338L14.13 2.576L6.636 10.07Zm6.787-8.201L1.591 6.602l4.339 2.76l7.494-7.493Z",
                                  fill: "currentColor"
                                }),
                            height: "16",
                            width: "16",
                            viewBox: "0 0 16 16",
                            xmlns: "http://www.w3.org/2000/svg"
                          }),
                      className: "btn btn-square",
                      onClick: handleButtonClick
                    })
              ],
              className: "\n    bg-slate-400\n    p-2\n    flex\n  "
            });
}

var make = Input;

export {
  make ,
}
/* react Not a pure module */
