// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as JsxRuntime from "react/jsx-runtime";

function Login(props) {
  var onSubmit = props.onSubmit;
  var match = React.useState(function () {
        return "";
      });
  var setText = match[1];
  var text = match[0];
  var handleKeyDown = function (e) {
    var key = e.key;
    if (key !== "Enter") {
      return ;
    }
    e.preventDefault();
    onSubmit(text);
    setText(function (param) {
          return "";
        });
  };
  var handleInputChange = function ($$event) {
    var value = $$event.currentTarget.value;
    setText(function (param) {
          return value;
        });
  };
  var handleButtonClick = function (param) {
    if (text === "") {
      return ;
    }
    onSubmit(text);
    setText(function (param) {
          return "";
        });
  };
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsxs("div", {
                    children: [
                      JsxRuntime.jsx("h2", {
                            children: "Welcome to Chat",
                            className: "card-title"
                          }),
                      JsxRuntime.jsx("input", {
                            className: "input input-bordered mr-1 w-full text-black",
                            placeholder: "Create username",
                            type: "text",
                            value: text,
                            onKeyDown: handleKeyDown,
                            onChange: handleInputChange
                          }),
                      JsxRuntime.jsx("div", {
                            children: JsxRuntime.jsx("button", {
                                  children: "Login",
                                  className: "btn btn-primary",
                                  onClick: handleButtonClick
                                }),
                            className: "card-actions justify-end"
                          })
                    ],
                    className: "card-body items-center text-center"
                  }),
              className: "card bg-neutral text-neutral-content rounded-lg"
            });
}

var make = Login;

export {
  make ,
}
/* react Not a pure module */
