// Generated by ReScript, PLEASE EDIT WITH CARE


function statusToString(status) {
  switch (status) {
    case "Pending" :
        return "Pending";
    case "Delivered" :
        return "Delivered";
    case "Seen" :
        return "Seen";
    
  }
}

export {
  statusToString ,
}
/* No side effect */
