// Generated by ReScript, PLEASE EDIT WITH CARE


var server = "server";

var clients = {};

function createMessage(from, message) {
  var time = new Date().getTime();
  return JSON.stringify(Object.fromEntries([
                  [
                    "from",
                    from
                  ],
                  [
                    "message",
                    message
                  ],
                  [
                    "timestamp",
                    time
                  ]
                ]));
}

function broadcast(from, message) {
  var jsonMsg = createMessage(from, message);
  Object.entries(clients).forEach(function (param) {
        if (param[0] !== from) {
          param[1].send(jsonMsg);
          return ;
        }
        
      });
}

function handleClient(username, client) {
  clients[username] = client;
  broadcast(server, username + " joined");
  client.on("message", (function (message) {
          broadcast(username, message);
        }));
  client.on("close", (function () {
          broadcast(server, username + " left");
        }));
}

var Socket;

export {
  Socket ,
  server ,
  clients ,
  createMessage ,
  broadcast ,
  handleClient ,
}
/* No side effect */
