// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Chat from "./Chat.bs.js";
import * as Js_exn from "rescript/lib/es6/js_exn.js";
import Fastify from "fastify";
import * as Nodeprocess from "node:process";
import Websocket from "@fastify/websocket";
import * as Caml_js_exceptions from "rescript/lib/es6/caml_js_exceptions.js";

var fastify = Fastify({
      logger: true
    });

fastify.register(Websocket);

fastify.addHook("preValidation", (async function (request, reply) {
        var path = request.routeOptions.url;
        var username = request.query["username"];
        if (path === "/chat" && username === undefined) {
          reply.code(403).send("Connection rejected");
          return ;
        }
        
      }));

fastify.register(async function (fastify) {
      fastify.get("/chat", {
            websocket: true
          }, (function (connection, request) {
              var username = request.query["username"];
              if (username !== undefined) {
                return Chat.handleClient(username, connection.socket);
              } else {
                fastify.log.error("TODO: WHAT TO DO HERE");
                return ;
              }
            }));
    });

async function start() {
  try {
    return await fastify.listen({
                port: 3000
              });
  }
  catch (raw_obj){
    var obj = Caml_js_exceptions.internalToOCamlException(raw_obj);
    if (obj.RE_EXN_ID === Js_exn.$$Error) {
      var m = obj._1.message;
      if (m !== undefined) {
        fastify.log.error(m);
      }
      Nodeprocess.exit(1);
      return ;
    }
    throw obj;
  }
}

await start(undefined);

export {
  fastify ,
  start ,
}
/* fastify Not a pure module */
