// Generated by ReScript, PLEASE EDIT WITH CARE


var $$Request = {};

var Reply = {};

var HTTP = {};

var $$WebSocket = {};

var Log = {};

export {
  $$Request ,
  Reply ,
  HTTP ,
  $$WebSocket ,
  Log ,
}
/* No side effect */
