// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_exn from "rescript/lib/es6/js_exn.js";
import * as Caml_js_exceptions from "rescript/lib/es6/caml_js_exceptions.js";

function parse(payload) {
  try {
    return {
            TAG: "Ok",
            _0: JSON.parse(payload)
          };
  }
  catch (raw_obj){
    var obj = Caml_js_exceptions.internalToOCamlException(raw_obj);
    if (obj.RE_EXN_ID === Js_exn.$$Error) {
      var msg = obj._1.message;
      if (msg !== undefined) {
        return {
                TAG: "Error",
                _0: msg
              };
      } else {
        return {
                TAG: "Error",
                _0: "Unknown error"
              };
      }
    }
    throw obj;
  }
}

function stringify(payload) {
  try {
    return {
            TAG: "Ok",
            _0: JSON.stringify(payload)
          };
  }
  catch (raw_obj){
    var obj = Caml_js_exceptions.internalToOCamlException(raw_obj);
    if (obj.RE_EXN_ID === Js_exn.$$Error) {
      var msg = obj._1.message;
      if (msg !== undefined) {
        return {
                TAG: "Error",
                _0: msg
              };
      } else {
        return {
                TAG: "Error",
                _0: "Unknown error"
              };
      }
    }
    throw obj;
  }
}

export {
  parse ,
  stringify ,
}
/* No side effect */
